spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/servidor_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:data.sql

app:
  allowed-origin: ${APP_ALLOWED_ORIGIN:http://localhost:3000}

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: servidores

jwt:
  secret: Y2hhdmUtc2VjcmV0YS1kby1qd3QtbXVpdG8tc2VndXJhLWV1bmljYQ==
  expiration: 300000
  refresh-expiration: 3600000

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    disable-swagger-default-url: true
    csrf:
      enabled: false 